#!/bin/bash
PROJECT_NAME="$1"
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
current_dir=$(pwd)
project_dir=$script_dir/..
toc_file=$project_dir/_doc/000-TOC.md
current=$(grep -hs ^  $toc_file || echo "")
cd $project_dir || exit
me=`basename "$0"`

echo "<!-- autogenerated file by ($me) -->" > $toc_file
echo "# Doc Index - $PROJECT_NAME" >> $toc_file
echo "<!-- TOC -->" >> $toc_file
while IFS= read -r line
do
  line=$(echo $line |  awk  -F "/"  '{print  "["$2"/"$3"]""(""/"$1"/"$2"/"$3")" }')
  if [[ "$line" == *\/\) ]]
  then
     echo "- $line"  >> $toc_file
  else
     echo "  - $line"  >> $toc_file
  fi

done <<< $(find -L _doc -maxdepth 2 -name "*.md" -type f | sort -r)
echo "<!-- /TOC -->" >> $toc_file

new=$(cat $toc_file || echo "")

cd $current_dir

if [ "$current" == "$new" ]; then
   exit 0
else
   echo "$toc_file has changed 'git add .' before commit"
   exit 127
fi
